### ISSUE TITLE
Question: How to load sprites from the local file system

### ISSUE THREAD

**Issue by Beanzilla** [replit/kaboom#68]
My root project directory is:

```
sprites/
index.html
game.js
style.css
```

In sprites directory I have:

```
hero-left.png
hero-right.png
hero-up.png
hero-down.png
wall.png
```

In games.js I have:

```js
kaboom({
  global: true,
  fullscreen: true,
  scale: 1,
  debug: true,
  // RGBA
  clearColor: [0, 0, 0, 1]
})

loadSprite('hero-left', 'hero-left.png')
loadSprite('hero-right', 'hero-right.png')
loadSprite('hero-up', 'hero-up.png')
loadSprite('hero-down', 'hero-down.png')
loadSprite('wall', 'wall.png')

const MOVE_SPEED = 120

scene('main', () => {
  layers(['bg', 'obj', 'ui'], 'obj')
  const map = [
    '######',
    '#        #',
    '#        #',
    '#        #',
    '######',
  ]
  const levelCfg = {
    width: 20,
    height: 20,
    '#': [sprite('wall'), solid(), 'wall'],
  }

  addLevel(map, levelCfg)

  const player = add([
    sprite('hero-right'),
    pos(30, 30),
    {
        dir: vec2(-1, 0),
    },
  ])

  keyDown('left', () => {
    player.changeSprite('hero-left')
    player.dir = vec2(1, 0)
    player.move(-MOVE_SPEED, 0)
  })
  keyDown('right', () => {
    player.changeSprite('hero-right')
    player.dir = vec2(-1, 0)
    player.move(MOVE_SPEED, 0)
  })
  keyDown('up', () => {
    player.changeSprite('hero-up')
    player.dir = vec2(0, -1)
    player.move(0, -MOVE_SPEED)
  })
  keyDown('down', () => {
    player.changeSprite('hero-down')
    player.dir = vec2(0, 1)
    player.move(0, MOVE_SPEED)
  })

  player.action(() => {
    player.resolve()
  })
})

start('main')
```

The result I get is an error:

```
failed to load hero-left.png
failed to load hero-right.png
failed to load hero-up.png
failed to load hero-down.png
failed to load wall.png
Error: sprite not found: "wall"
at sprite (https://kaboomjs.com/lib/0.5.0/kaboom.js:56:3338)
at Object.init (file:///home/beanzilla/projects/kaboom/my_game/game.js:30:11)
at goSync (https://kaboomjs.com/lib/0.5.0/kaboom.js:55:14756)
at https://kaboomjs.com/lib/0.5.0/kaboom.js:56:396
at frame (https://kaboom.js.com/lib/0.5.0/kaboom.js:55:3425)
```

**Comment by Beanzilla** [comment]
Nevermind, I just learned that since it's JavaScript it's sandboxed. (Which means what I am asking about is irrelevant/invalid)

Sorry for anyone racking their brains over a simple user error.

**Comment by Shyentist** [comment]
I am having the same issue, but I don't understand your realization. How did you solve this?

**Comment by willbidstrup** [comment]
+1 I am running into this issue and trying for a fix.

**Comment by slmjkdbtl** [comment]
Browser and WebGL won't allow JavaScript to load files from local filesystem, the only way is to use a server to serve static files. 

There's a lot of static file server softwares, the easiest one should be

python3 -m http.server

see this [this MDN doc](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server) for more info.

**Comment by willbidstrup** [comment]
Thanks for the reply @slmjkdbtl, I figured after trial and error. Github works as well to host although I won't use that ongoing. Thanks for clarifying and hope this thread helps other too. In short - put your assets on a server somewhere if you are developing locally.
